# Generated by Django 2.0.7 on 2018-08-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
            ],
        ),
    ]
