# Generated by Django 2.0.7 on 2018-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modevideo',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
